# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/docs',
                'doc_host': 'https://inpap.github.io',
                'git_url': 'https://github.com/inpap/docs',
                'lib_path': 'docs'},
  'syms': {'docs.core': {'docs.core.foo': ('core.html#foo', 'docs/core.py')}}}
